Вариант реализации :)
EvilBeaver/odminus pull request #3
Opened 2018-02-20 18:08 UTC by WizaXxX

Привет. Посмотри пожалуйста такой вариант реализации. 
Общий смысл, на сервера вешаем "агентов" простой скрипт по сбору данных.
Данные прилетают к нам, мы их сохраняем. Получается на 1 этапе просто веб морда для серверов, кластеров, баз и т.д
На 2 этапе добавляем настройки для работы с rac/ras и делаем демона который удаленно через тот же WMI (или что то другое) запускает для нужных нам кластеров ras^ы.
И реализуем взаимодействие через rac/ras.

С web^ом вообще не работал толком, поэтому есть некоторое дублирование разметки, на некоторых вьюхах. 
С oscript тоже не работал :( Но теперь буду 👍

2018-02-23 08:12 UTC, EvilBeaver requested changes
Я на след. неделе солью этот PR в отдельную ветку и потаскаю из него кусочки. Но целиком вливать кажется не нужно

2018-02-23 08:12 UTC, EvilBeaver commented on src/controllers/home.os
> +	мНастройки = Настройки.ГлобальныеНастройки;
Срок жизни контроллера - 1 http запрос. Писать глобальные настройки уровня приложения здесь нельзя. Вернее, можно, но через базу данных или монопольный файл. Если это переменная в общем модуле, то при одновременном обращении с 2 разных машин будет хаос и непредсказуемый результат.

Я сейчас в отпуске и глубоко изучить код смогу только на будущей неделе. Однозначно придется что-то изменить, возможно, серьезно.

2018-02-23 08:12 UTC, EvilBeaver commented on src/model/modules/Настройки.os
> +		СтруктураНастроек.Вставить("Серверы", 				Серверы.Инициализировать());
Кажется, что надежнее эти данные всегда получать из RAS, а не хранить в файле. Он может потерять актуальность, если зайти в 1С-консоль и удалить какой-то сервер или еще какие-то настройки изменить. Получится, что файл перестанет отражать реальность

2018-02-25 13:07 UTC, WizaXxX commented on src/controllers/home.os
> +	мНастройки = Настройки.ГлобальныеНастройки;
Я думал в дальнейшем просто добавить именно монопольный доступ к файлу.
Тем более раз делать будем через rac/ras нам не придется хранить большое количество файлов. Плюс если не будем использовать БД у нас будет меньше зависимостей и проще будет разворачивать сервис.

2018-02-25 13:08 UTC, WizaXxX commented on src/model/modules/Настройки.os
> +		СтруктураНастроек.Вставить("Серверы", 				Серверы.Инициализировать());
Ок. Может создадим какой то канал в телеграмме или еще где, что бы можно было по оперативнее принимать решения?

2018-02-26 07:14 UTC, EvilBeaver commented on src/model/modules/Настройки.os
> +		СтруктураНастроек.Вставить("Серверы", 				Серверы.Инициализировать());
https://gitter.im/EvilBeaver/odminus

2019-07-24 07:27 UTC, closed without merging