Develop
EvilBeaver/odminus pull request #6
Opened 2018-11-02 16:54 UTC by otymko

Реализовано:
- metroui и jquery перенесены в статику
- реализована страница с сессиями по информационной базе (немного ajax)
- мелкие доработки контроллера infobase для авторизации в информационной базе

2018-11-02 17:02 UTC, otymko commented
@EvilBeaver

2018-11-03 14:14 UTC, EvilBeaver requested changes
В целом - все супер. Есть несколько вопросов по UUID кластеров в коде.
Спасибо!

2018-11-03 14:14 UTC, EvilBeaver commented on src/controllers/session/index.cshtml
> +                url: urlAuthDB + '?cluster=657583b5-ec6b-4dc5-9043-2063a204db95&db=' + element_select.val(),
Хардкод UID кластера кажется тут лишним, не?

2018-11-03 14:14 UTC, EvilBeaver commented on src/controllers/session/index.cshtml
> +                url: urlAuthDB + '?cluster=657583b5-ec6b-4dc5-9043-2063a204db95&db=' + element_select.val(),
И здесь

2018-11-03 14:14 UTC, EvilBeaver commented on src/model/modules/ОбщегоНазначения.os
> +Функция РазложитьСтрокуВМассивПодстрок(Знач Строка, Знач Разделитель = ",", Знач ПропускатьПустыеСтроки = Неопределено, СокращатьНепечатаемыеСимволы = Ложь) Экспорт
Штатная функция СтрРазложить из 1С не подходит?

2018-11-03 16:18 UTC, otymko commented on src/controllers/session/index.cshtml
> +                url: urlAuthDB + '?cluster=657583b5-ec6b-4dc5-9043-2063a204db95&db=' + element_select.val(),
Недосмотрел, сейчас поправлю)

2018-11-03 16:18 UTC, otymko commented on src/controllers/session/index.cshtml
> +                url: urlAuthDB + '?cluster=657583b5-ec6b-4dc5-9043-2063a204db95&db=' + element_select.val(),
Аналогичная ситуация

2018-11-03 16:19 UTC, otymko commented on src/model/modules/ОбщегоНазначения.os
> +Функция РазложитьСтрокуВМассивПодстрок(Знач Строка, Знач Разделитель = ",", Знач ПропускатьПустыеСтроки = Неопределено, СокращатьНепечатаемыеСимволы = Ложь) Экспорт
Есть СтрРазделить - в принципе ее будет достаточно. Сейчас поменяю.

2018-11-03 16:55 UTC, otymko commented on src/model/modules/ОбщегоНазначения.os
> +Функция РазложитьСтрокуВМассивПодстрок(Знач Строка, Знач Разделитель = ",", Знач ПропускатьПустыеСтроки = Неопределено, СокращатьНепечатаемыеСимволы = Ложь) Экспорт
Исправлено

2018-11-03 16:55 UTC, otymko commented on src/controllers/session/index.cshtml
> +                url: urlAuthDB + '?cluster=657583b5-ec6b-4dc5-9043-2063a204db95&db=' + element_select.val(),
Исправлено

2018-11-03 16:56 UTC, otymko commented
@EvilBeaver 
Поправил. Там еще изменения из dev подъехали по sidebar-у

2018-11-03 19:00 UTC, merged